<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<restMockResponse>
    <body>[&#13;
	{&#13;
		"name": "admin",&#13;
		"username": "admin",&#13;
		"role": "administrator",&#13;
		"active": "0"&#13;
	},&#13;
	{&#13;
		"name": "Lucas Hale",&#13;
		"username": "lhale",&#13;
		"role": "manager",&#13;
		"active": "1"&#13;
	},&#13;
	{&#13;
		"name": "Holly Salas",&#13;
		"username": "hsalas",&#13;
		"role": "manager",&#13;
		"active": "1"&#13;
	},&#13;
	{&#13;
		"name": "Lilly Ayers",&#13;
		"username": "layers",&#13;
		"role": "employee",&#13;
		"active": "1"&#13;
	},&#13;
	{&#13;
		"name": "Geoffrey Jordan",&#13;
		"username": "gjordan",&#13;
		"role": "employee",&#13;
		"active": "1"&#13;
	},&#13;
	{&#13;
		"name": "Monica Barry",&#13;
		"username": "mbarry",&#13;
		"role": "employee",&#13;
		"active": "0"&#13;
	},&#13;
	{&#13;
		"name": "Herman Sandoval",&#13;
		"username": "hsandoval",&#13;
		"role": "employee",&#13;
		"active": "1"&#13;
	}&#13;
]&#13;
</body>
    <contentEncodings/>
    <headerQueries>
        <headerQuery>
            <header>Accept</header>
            <matchAny>false</matchAny>
            <matchCase>false</matchCase>
            <matchRegex>false</matchRegex>
            <query>application/json</query>
        </headerQuery>
    </headerQueries>
    <httpHeaders>
        <httpHeader>
            <name>Content-Type</name>
            <value>application/json</value>
        </httpHeader>
    </httpHeaders>
    <httpStatusCode>200</httpStatusCode>
    <id>7zh7CH</id>
    <jsonPathExpressions/>
    <methodId>0leXBd</methodId>
    <name>Success - json</name>
    <parameterQueries/>
    <status>ENABLED</status>
    <usingExpressions>false</usingExpressions>
    <xpathExpressions/>
</restMockResponse>
